### ISSUE TITLE
Test sample

### ISSUE THREAD

**Issue by pcordonet** [marcosgambeta/sqlrddpp#1]
Hi Marco,

Are you try to compile / link any sample ?

I tried to demo01.prg and i have this error "fatal error LNK1181: no se puede abrir el archivo de entrada 'hbrtl.lib'"

cmdline: hbmk2 demo01.prg sqlrddpp.hbc -i..\include

Any tips ?

Thank you.

**Comment by marcosgambeta** [comment]
Hi Pere,

I am creating my own tests. The samples folder need to be revised yet.

I am testing with Harbour 3.2.0dev and VS2019.

Which version of Visual C++ are you using ? SGBD ?

Can you inform the result of the command 'harbour -build' ?

**Comment by pcordonet** [comment]
Hi, Marco,

I'm working with xharbour commercial, with SQLRDD, but i need move harbour.
If you need make some tests, i'll try.

I'm work with Harbour 3.2.0dev and VS2022.

Result of  'harbour -build':

Harbour 3.2.0dev (r2302030146)
Copyright (c) 1999-2021, https://harbour.github.io/

Harbour Build Info
---------------------------
Version: Harbour 3.2.0dev (r2302030146)
Compiler: Microsoft Visual C++ 19.29.30038 (64-bit)
Platform: Windows Server 2016 10.0
PCode version: 0.3
ChangeLog last entry: 2023-02-03 02:46 UTC+0100 Przemyslaw Czerpak (druzus/at/poczta.onet.pl)
ChangeLog ID: 6d718be3edcaeabdd8ab3d3742035283cc7b4162
Built on: Mar  2 2023 09:15:29
Build options: (tracing) (C++ mode) (Clipper 5.3b) (Clipper 5.x undoc)

is this right version?

Thank you.
Pere
---------------------------
