### ISSUE TITLE
Error Compiling Under Ubuntu 22

### ISSUE THREAD

**Issue by mhsabado** [marcosgambeta/sqlrddpp#12]
Hi Marcos,

I have encountered the following error when compiling HarbourPP + SQLRDDPP under Ubuntu 22.

Thanks,
Mario

*********************************************************************************************************
../../../../../../source/sqlsrodbc.c: In function ‘void HB_FUN_SR_GETCONNECTOPTION()’:
../../../../../../source/sqlsrodbc.c:1005:16: error: invalid conversion from ‘char’ to ‘SQLPOINTER’ {aka ‘void*’} [-fpermis]
 1005 |    buffer[0] = '\0';
      |                ^~~~
      |                |
      |                char
hbmk2[sqlrddpp]: Error: Running C/C++ compiler. 1
g++ -c -O3  -W -Wall -pipe -I'/home/mhsabado/win_d/harbourpp/include' -I../../../../../../include -I../../../../../../sourcc
**********************************************************************************************************

**Comment by marcosgambeta** [comment]
To compile in C++, the flag below is required:

-fpermissive

Try this:

hbmk2 sqlrddpp,hbp -cflag=-fpermissive

**Comment by mhsabado** [comment]
Hi Marcos,

It compiles successfully after the adding -fpermissive flag.

Thank you!

Mario
