### ISSUE TITLE
Problem using set index on open query

### ISSUE THREAD

**Issue by marcoprodata** [marcosgambeta/sqlrddpp#18]
Caro Marcos,

Na versão do xHarbour era possível executar o seguinte código:

conexao = 'pgs=192.168.10.10;uid=sysadmin;pwd=v8xy14;dtb=hrb_quito;prt=5440'
x = Sr_Addconnection( CONNECT_POSTGRES, conexao)

xQuery:="select codigo, descricao from itens limit 200" 
use &xQuery via "SQLRDD" alias titens
set index to "codigo"   // criava um indice virtual para a query aberta
seek "000825"

hoje esse código dá erro de:
Bound error: array access

É possível executar algo parecido com a atual versão para harbour?

**Comment by marcosgambeta** [comment]
Teste, por favor, com o alteração abaixo:
https://github.com/marcosgambeta/sqlrddpp/commit/b8d2334886795907f59177f93e7ee893e5dbb463

**Comment by marcoprodata** [comment]
Continua o mesmo erro:

Error BASE/1132  Bound error: array access
Called from CHARACTER:__OPARRAYINDEX(0)
Called from SR_WORKAREA:SQLORDERLISTADD(7281)
Called from ORDLISTADD(0)
Called from MAIN(18)

exatamente na linha do
set index to "codigo"

**Comment by marcosgambeta** [comment]
Poderia informar o que tem na linha 7281 (sqlrdd2.prg) da sua instalação da SQLRDD ?
Aqui eu consegui reproduzir o erro citado por você no início.  Com a alteração,, o erro não ocorreu mais.

**Comment by marcoprodata** [comment]
![image](https://github.com/marcosgambeta/sqlrddpp/assets/16479713/42efa6de-06bf-45f9-a011-07eaabc27fdb)

**Comment by marcosgambeta** [comment]
Obrigado. Adicionei um novo teste que está funcionando sem dar erro no meu ambiente de desenvolvimento:
https://github.com/marcosgambeta/sqlrddpp/commit/178d48f227f3f6f0634aa363f4f33babad26b4a9
Entretanto, o SEEK está falhando em localizar o registro. O comando LOCATE funciona. Vou revisar o código envolvido. Pode ser alguma diferença entre o Harbour e o xHarbour na camada de RDD.
Caso o teste dê erro no seu ambiente, experimente fazer uma compilação limpa da SQLRDD.

**Comment by marcosgambeta** [comment]
Mais um detalhe. A falha no SEEK ocorre apenas quando se abre a tabela usando uma consulta. Se ela é aberta da forma abaixo, o SEEK funciona:
```
USE test VIA "SQLRDD" ALIAS test
SET INDEX TO "id" // create a virtual index
SEEK 15
```

**Comment by marcoprodata** [comment]
Então, no xHarbour era possível criar esses indices virtuais, mesmos nas tabelas também virtuais, abertas via consulta, isso não será mais possível no harbour?

**Comment by marcosgambeta** [comment]
Nos testes que fiz aqui, o índice virtual está sendo criado corretamente.  Mas há algo impedindo que o SEEK localize o registro. Achando e resolvendo este problema, vai funcionar da mesma forma que no xHarbour.

**Comment by marcoprodata** [comment]
Refazendo os teste com uma estrutura 100% limpa, realmente o set index está funcionando, ordenando a consulta, mas o seek realmente continua não funcionando, mas não dá mais o erro.

**Comment by marcosgambeta** [comment]
Com respeito ao erro, pode-se considerar corrigido.

Com respeito ao SEEK, não é um erro mas sim o comportamento da SQLRDD. Revisei o código-fonte e o retorno do SEEK é sempre .F. quando se trata de uma consulta (query). Quando é uma tabela, funciona normal.

Eu cheguei a pensar que fosse um erro na adaptação da SQLRDD original para o Harbour, mas o funcionamento dela é assim mesmo.

Veja a linha 4056 do arquivo sqlrdd2.prg:

```
ElseIf ::lISAM .and. ::oSql:nSystemID == SYSTEMID_POSTGR
```

Note que ::lISAM precisa ser .T. para o SEEK funcionar. Ele é .T. quando se abre uma tabela, mas .F. quando se abre uma consulta.

A solução, com o código atual, seria usar o LOCATE.

**Comment by marcoprodata** [comment]
Ok, com o locate tá funcionando, já é o suficiente, muito obrigado pelo suporte.
