### ISSUE TITLE
Error com DbUseArea()

### ISSUE THREAD

**Issue by sygecom** [marcosgambeta/sqlrddpp#19]
Marcos,
Com essas ultimas alterações do SQLRDD que eu não atualizava desde Janeiro/2024 passou a dar o erro abaixo, que não tinha anteriormente.

Error BASE/1068  Erro nos parƒmetros: acesso de array
Called from source\sqlrdd2.prg->SR_WORKAREA:LOADREGISTEREDTAGS(688)
Called from source\sqlrdd2.prg->SR_WORKAREA:SQLOPENAREA(6884)
Called from source\syg_rdd.prg->USE_ARQ(1331)
Called from source\errorsys.prg->SYG_DEFERROR(137)
Called from source\errorsys.prg->(b)ERRORSYS(19)
Called from source\anexar_img.prg->DBSELECTAREA(0)
Called from source\sagi.prg->VEREFICA_LOGIN(2202)
Called from source\sagi.prg->(b)MAIN(1662)
Called from source\htimer.prg->HWG_TIMERPROC(105)
Called from source\hwindow.prg->HWG_ACTIVATEMDIWINDOW(0)
Called from source\hwindow.prg->HMAINWINDOW:ACTIVATE(396)
Called from source\sagi.prg->MAIN(1722)

Data e Hora........: 29/02/2024 - 01:35:26
Versão compilador..: HwGUI 2.17 Harbour 3.2.0dev (r2402161723)
Compilador C/C++...: Borland/Embarcadero C++ 7.4 (32-bit)
Banco de Dados.....: POSTGRESQL NATIVE - PostgreSQL 13.12, compiled by Visual C++ build 1914, 64-bit

Até tentei voltar esse commit abaixo para testar, mesmo assim da erro.
https://github.com/marcosgambeta/sqlrddpp/commit/fa273a2e813dea08dec33743cfcae068f083d1f3

Abaixo minha FUNCTION USE_ARQ
```
*===============================================================================
* FUNCTION Use_Arq(cArquivo,cAlias,iShared,iLeitura,iTemp,iabre_auto)
*-------------------------------------------------------------------------------
*
*-------------------------------------------------------------------------------
*  cArquivo  : Nome do Arquivo
*  cAlias    : Nome do Apelido(ALIAS)
*  iShared   : .f.=Exclusivo - .t.=Compartilhado
*  iLeitura  : .t.=sómente Leitura - .f.=Leitura e Gravação
*  iTemp     : .t.=usa uma tabela temporaria - .f.=abre uma tabela normal
*  iabre_auto: .t. ou .f. =força abertura - nil=não abre na abertura do modulo
*===============================================================================
FUNCTION USE_ARQ(cArquivo,cAlias,iShared,iLeitura,iTemp,iabre_auto)
Local oERROR
Local cDriver  := "DBFCDX"
Local lResp    :=.t.
Local nTENTATIVA_RDD:=0

IF UPPER(ALLTRIM(cArquivo))='TEMPDROPCO' .OR. cArquivo='tempdropco' // TABELA TEMPORARIA DO SQLRDD
//   showmsg('tentou abrir a tabela temporaria do sqlrdd')
   Return .T.
ENDIF

IF cAlias=Nil
   IF iShared= .T.   // SE FOR COMPARTILHADO
      IF iTemp = .F.
         IF iabre_auto=Nil
            Return(.T.)
         ENDIF
      ENDIF
   ENDIF
   cAlias=cArquivo
ENDIF

if iTemp = .F.
   cDriver:="SQLRDD"
endif

if iTemp = .T.
   cDriver:="DBFCDX"
endif

IF cDriver="SQLRDD" .OR. cDriver="SQLLIB"
   IF _plTABELAS_EXC()
      AADD( _paTABELAS_EXC() ,ALLTRIM(UPPER(cArquivo))) // ADICIONA NO VETOR PUBLICO OS NOMES DAS TABELAS QUE PRECISA EXCLUIR OS INDICES
   ENDIF
ENDIF

do while .t.

   IF SELECT(cAlias)=0
      *TRY
         DBSELECTAREA(0) // SELECIONA A PROXIMA AREA LIVRE
         DbUseArea(.t.,cDriver,cArquivo,cAlias,iShared,iLeitura,,)
      /*catch oERROR
         nTENTATIVA_RDD:=nTENTATIVA_RDD+1
         IF nTENTATIVA_RDD>=3
            lResp := HWG_MsgRetryCancel( "Erro ao Tentar Abrir a Tabela: " + cArquivo + ", Favor revisar a conexão com o Servidor ! " + oERROR:Description )
            IF lResp
               REABRE_CONEXAO()
               loop
            ELSE
               Focaliza_App(_PCNOMEDIALOGMAIN())
               Return(.F.)
            ENDIF
         ELSE
            loop
         ENDIF
      END*/
      IF NetErr()
         lResp := HWG_MsgRetryCancel( "Sistema em Uso em Modo Exclusivo por Outra Estação no Momento !"  )
         IF lResp
            loop
         ELSE
            Return(.F.)
         ENDIF
      else
         SELECT(cAlias)
         Return(.T.)
      endif
   ELSE
      &cAlias->(DbCloseArea())  // FECHA PARA ABRIR DE NOVO
      LOOP
   ENDIF
enddo
Return(.F.)

```

**Comment by sygecom** [comment]
Marcos,
Esqueci de comentar nesse meu erro já eliminei o xhb.hbc
Amanhã vou testar colocando de volta a xhb.hbc é ver se esse erro permanece ou não. Só pra saber se é o xhb que estava contornado algo.

**Comment by marcosgambeta** [comment]
A origem do erro vem do recurso do xHarbour de acessar elementos de uma string como se fosse array.
Exemplo:
```
c := cString[5] // acessa o quinto elemento da string
```
Casos assim, caso apareça algum, precisam ser substituídos por SubStr.
Exemplo:
```
c := SubStr(cString, 5, 1)
```

**Comment by marcosgambeta** [comment]
Fiz algumas correções no código-fonte relacionadas com este erro. Caso se depare com mais algum caso, basta informar onde ocorreu o erro que farei a correção o mais breve possível.

**Comment by sygecom** [comment]
Obrigado, vou baixar e testar.

**Comment by sygecom** [comment]
Deu certo mestre, vou seguir em frente sem xhb.hbc, vou encerrar esse ticket
