### ISSUE TITLE
Firebird via ODBC using SQLEX RDD Error

### ISSUE THREAD

**Issue by mhsabado** [marcosgambeta/sqlrddpp#3]
Hi Marcos,

I have tested the tests/firebird2.prg file and used an ODBC connection instead.  It works fine with SQLRDD but when I use SQLEX, I have the following error below:

nConnection := sr_AddConnection(CONNECT_ODBC,"driver=Firebird/InterBase(r) driver;server=localhost;port=3050;uid=SYSDBA;pwd=masterkey;database=c:\firebird\firebird_4_0\data\test.fdb;client=fbclient.dll;charset=ISO8859_1;")

**********************************************************
C:\sqlrddpp\tests>firebird2                                                                                                                                     
Error SQLRDD/0  SQL execution error at dbGoTop, return code: -1, state: HY000, description: [ODBC Firebird Driver][Firebird]Dynamic SQL Error                   
SQL error code = -104                                                           
Unexpected end of command - line 1, column 10.                                  
Called from DBGOTOP(0)                                                          
Called from MAIN(61)                                                            
Error SQLEX/1010  Argument error: "TEST"                                        
Called from DBGOTOP(0)                                                          
Called from MAIN(61)
C:\sqlrddpp\tests>
***************************************************

Thanks,
Mario

**Comment by marcosgambeta** [comment]
Hi Mario,

Please, test again checking the return of the connection:

 nConnection := sr_AddConnection( ... )

IF nConnection < 0
   alert("Connection error. See sqlerror.log for details.")
   QUIT
ENDIF

**Comment by mhsabado** [comment]
Hi Marcos,

It works now after your last update.  I also tried with ODBC via SQLRDD and
SQLEX and both tests works fine.

Thank you very much!

Best regards,
Mario

**Comment by mhsabado** [comment]
Hi Marcos,

Not really sure what happened because I made sure I'm running the test correctly (drop table, recompile) and it all went well.  But when I re-run the same test, I got the following error.   

Thanks,
Mario

*****************************************************
C:\sqlrddpp\tests>odbcfirebird2
Error SQLRDD/0  SQL execution error at PrepareInsertStmt, return code: -1, state: HY000, description: [ODBC Firebird Driver][Firebird]Dynamic SQL Error
SQL error code = -104
Token unknown - line 1, column 22
,.
Called from DBAPPEND(0)
Called from MAIN(65)
*******************************************

**Comment by marcosgambeta** [comment]
Wich version of Firebird are you using ?

I'm using 3.0.11. But I am planning to test with Firebird 4 and 5 as soon as possible.

**Comment by marcosgambeta** [comment]
Dont forget to see the file sqlerror.log. Maybe the messages can help to identify the problem.

**Comment by mhsabado** [comment]
Hi Marcos,

I'm using Firebird 4 Server and Client Lib/DLL.  No sqlerror.log was
generated but the table was successfully created.

******************************************************
C:\sqlrddpp\tests>odbcfirebird2.exe
Error SQLRDD/0  SQL execution error at dbGoTop, return code: -1, state:
HY000, description: [ODBC Firebird Driver][Firebird]Dynamic SQL Error
SQL error code = -104
Unexpected end of command - line 1, column 18.
Called from DBCREATE(0)
Called from MAIN(58)
Error SQLEX/1010  Argument error: "TEST"
Called from DBCREATE(0)
Called from MAIN(58)
************************
[image: image.png]

Thanks,
Mario

**Comment by mhsabado** [comment]
Hi Marcos,

I installed Firebird 3.0 and recompiled/run the same test using respective
DLL/Lib but got the same error and no sqlerror.log was generated.

Using SQLRDD works fine but the performance is at par with native
connection.  Once SQLEX is resolved, it should be more than 50% faster than
native and 30% faster than PostgreSQL native connection (based on old
(2009) xHarbour SQLRDD version).
******************************************************
C:\sqlrddpp\tests>odbcfirebird2
Error SQLRDD/0  SQL execution error at dbGoTop, return code: -1, state:
HY000, description: [ODBC Firebird Driver][Firebird]Dynamic SQL Error
SQL error code = -104
Unexpected end of command - line 1, column 18.
Called from DBCREATE(0)
Called from MAIN(58)
Error SQLEX/1010  Argument error: "TEST"
Called from DBCREATE(0)
Called from MAIN(58)
*************************************************

Thanks,
Mario

**Comment by marcosgambeta** [comment]
Please, test again after the commit:
https://github.com/marcosgambeta/sqlrddpp/commit/d648a775cc8ed10b105b21129822184f6312b7dc

**Comment by mhsabado** [comment]
HI Marcos,

Works fine now!!!

Please see the result of my local test below.  Firebird took 0.41 minute
while Postgres took 1.04 min.
Only remains now is Postgres DSN-Less ODBC but this is already a great feat.

Many thanks for your usual support and making this library achieve one of
its best potential...

Best regards,
Mario

******************************************************
Connecting to dsn=FBODBC;

RDD in use          : SQLEX

09/21/23 22:59:51.928

Uploading... stokmast (166976 records)

Elapsed:           0.41 min
******************************************************
Connecting to dsn=pgs9;

RDD in use          : SQLEX

09/21/23 23:08:26.207

Uploading... stokmast (166976 records)

Elapsed:           1.04 min
*****************************************************

**Comment by mhsabado** [comment]
Hi Marcos,

Firebird's upcoming version 5 will have a "SKIP LOCKED" for UPDATE and
DELETE operations feature.  I think this is a great feature that may
resolve many "DEADLOCK"  issues in a high user concurrency environment.

Best regards,
Mario
