### ISSUE TITLE
PostgreSQL ODBC via SQLEX RDD Error

### ISSUE THREAD

**Issue by mhsabado** [marcosgambeta/sqlrddpp#5]
Hi Marcos,

Testing PostgreSQL (v9.3) using "PostgreSQL UNICODE" driver with your latest commit, the error reduced to the following:

Error SQLEX/1020  Data type error: data type origin: 128 - data type target 1024
Called from MAIN(71)
**********************************
...........................
  IF reccount() < 100
      FOR n := 1 TO 100
         APPEND BLANK
         REPLACE ID      WITH n
         REPLACE FIRST   WITH "FIRST" + hb_ntos(n)
         REPLACE LAST    WITH "LAST" + hb_ntos(n)
         REPLACE AGE     WITH n + 18
         REPLACE DATE    WITH date() - n
         REPLACE MARRIED WITH iif(n / 2 == int(n / 2), .T., .F.)  //Line #71
         REPLACE VALUE   WITH n * 1000 / 100
      NEXT n
   ENDIF
...................
************************

Thanks,
Mario

**Comment by marcosgambeta** [comment]
Mario,

Please, try again using the options BoolsAsChar=0 and TrueIsMinus1.

See the commit below:
https://github.com/marcosgambeta/sqlrddpp/commit/9a47f251fd541cbfe268d9a7e59e584a0b60bd30

**Comment by mhsabado** [comment]
Hi Marcos,

I have tested the odbcpgsql1 and odbcpgsql2 and confirm that using SQLEX
already works fine now.

Many thanks for this Marcos!

Regards,
Mario
