### ISSUE TITLE
Error on CLOSE DATABASE

### ISSUE THREAD

**Issue by pcordonet** [marcosgambeta/sqlrddpp#7]
Hi Marcos,

I tried tests\mysql1.prg, and work fine, but on "CLOSE DATABASE" i have this error:

Error DBCMD/1015  Argument error: DBUSEAREA
Called from DBUSEAREA(0)
Called from SR_WRITEDBLOG(753)
Called from SR_MYSQL:EXEC(409)
Called from SR_EXISTTABLE(1267)
Called from MAIN(38)

Error DBCMD/1015  Argument error: DBUSEAREA
Called from DBUSEAREA(0)
Called from SR_WRITEDBLOG(753)
Called from SR_CONNECTION:ROLLBACK(895)
Called from SR_MYSQL:ROLLBACK(297)
Called from SR_ENDCONNECTION(1345)
Called from SR_END(1459)

And i can't solve error.

if comented "sr_StartLog(nConnection)" works fine.

Thank you.

Can you help me?
Pere

**Comment by mhsabado** [comment]
Hi Pere,

Please try to insert "sr_StopLog(nConnection)" after the CLOSE DATABASE

Mario

**Comment by pcordonet** [comment]
Hi Marcos.
Works fine.

Can you update tests, please ?

Thank you,

**Comment by marcosgambeta** [comment]
Tests updated:
https://github.com/marcosgambeta/sqlrddpp/commit/16c11923712c03fbb922fb658a7c61fd12557f38
